apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: tcp9200
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: tcp9300
    port: 9300
    targetPort: 9300
    protocol: TCP
  type: NodePort
