apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: registry.cn-hangzhou.aliyuncs.com/xiaobaxi/docker/elasticsearch
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/etc/localtime"
          name: timezone
      volumes:
        - name: timezone
          hostPath:
            path: "/etc/localtime"
