apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-slave-2
  labels:
    app: rabbitmq-slave-2
spec:
  ports:
    - port: 5672
      name: rabbitmq
    - port: 4369
      name: epmd
    - port: 25672
      name: erlang
    - port: 15672
      name: management
      nodePort: 31607
    - port: 5671
      name: ssl
      nodePort: 32719
  selector:
    app: rabbitmq-slave-2
  type: NodePort
