apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-master
  labels:
    app: rabbitmq-master
spec:
  containers:
  - name: rabbitmq-master
    image: cloud/rabbit-server
    imagePullPolicy: Always
    ports:
    - containerPort: 4369
      name: epmd
    - containerPort: 5672
      name: rabbitmq
    - containerPort: 15672
      name: management
    - containerPort: 5671
      name: ssl
    - containerPort: 25672
      name: erlang
