apiVersion: v1
kind: Service
metadata:
  name: portal-minio
  labels:
    app: portal-minio
spec:
  ports:
    - port: 9000
      name: rabbitmq
      nodePort: 30009
  selector:
    app: portal-minio
  type: NodePort
