apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec: 
  ports:
  - name: tcp-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: tcp-6380
    port: 6380
    protocol: TCP
    targetPort: 6380
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
