apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: registry.cn-hangzhou.aliyuncs.com/xiaobaxi/docker/redis
        imagePullPolicy: Always
